interface ChargerModel {
    id?: number;
    station_name: string | null,
    ev_connector_types: string[] | null,
    ev_network: string | null,
    latitude: number,
    longitude: number,

    ev_network_web?: string | null,
    access_code?: string | null,
    access_days_time?: string | null,
    access_detail_code?: string  | null,
    cards_accepted?: string  | null,
    string_last_confirmed?: string | null,
    expected_string?: string  | null,
    fuel_type_code?: string | null,
    groups_with_access_code?: string | null,
    maximum_vehicle_class?: string | null,
    open_string?: string | null,
    owner_type_code?: string | null,
    restricted_access?: string | null,
    status_code?: string | null,
    funding_sources?: string | null,
    facility_type?: string | null,
    station_phone?: string | null,
    upstringd_at?: string | null,
    geocode_status?: string | null,
    city?: string | null,
    country?: string | null,
    intersection_directions?: string | null,
    plus4?: string | null,
    state?: string | null,
    street_address?: string | null,
    zip?: string | null,
    bd_blends?: string | null,
    cng_dispenser_num?: string | null,
    cng_fill_type_code?: string | null,
    cng_has_rng?: string | null,
    cng_psi?: string | null,
    cng_renewable_source?: string | null,
    cng_total_compression?: string | null,
    cng_total_storage?: string | null,
    cng_vehicle_class?: string | null,
    e85_blender_pump?: string | null,
    e85_other_ethanol_blends?: string | null,
    ev_dc_fast_num?: string | null,
    ev_level1_evse_num?: string | null,
    ev_level2_evse_num?: number | null,
    ev_other_evse?: string | null,
    ev_pricing?: string | null,
    ev_renewable_source?: string | null,
    ev_workplace_charging?: boolean | null,
    hy_is_retail?: string | null,
    hy_pressures?: string | null,
    hy_standards?: string | null,
    hy_status_link?: string | null,
    lng_has_rng?: string | null,
    lng_renewable_source?: string | null,
    lng_vehicle_class?: string | null,
    lpg_nozzle_types?: string | null,
    lpg_primary?: string | null,
    ng_fill_type_code?: string | null,
    ng_psi?: string | null,
    ng_vehicle_class?: string | null,
    rd_blended_with_biodiesel?: string | null,
    rd_blends?: string | null,
    rd_blends_fr?: string | null,
    rd_max_biodiesel_level?: string | null,
    nps_unit_name?: string | null,
    access_days_time_fr?: string | null,
    intersection_directions_fr?: string | null,
    bd_blends_fr?: string | null,
    groups_with_access_code_fr?: string | null,
    ev_pricing_fr?: number | null
};

export default ChargerModel;